# Dockerfile-wordpress
FROM wordpress:latest

WORKDIR /var/www/html

# Copy custom themes and plugins (if needed)
# COPY custom-theme/ wp-content/themes/custom-theme/
# COPY custom-plugin/ wp-content/plugins/custom-plugin/

EXPOSE 80

ENV WORDPRESS_DB_HOST=localhost
ENV WORDPRESS_DB_USER=corewpx
ENV WORDPRESS_DB_PASSWORD=palazzo
ENV WORDPRESS_DB_NAME=corewpx

VOLUME /var/www/html/wp-content

USER www-data
